### ISSUE TITLE
Некорректная логика работы

### ISSUE THREAD

**Issue by Bratchvv** [Romchansky/brain-acad-labs#2]
Этот цикл здесь не к месту)
Либо убрать его вовсе, либо переделать на цикл с индексами и выводить по порядку.
https://github.com/Romchansky/brain-acad-labs/blob/d217649025e0d5fdacc1322b7f047c091f720c2d/Lab9/src/ua/zp/brainacad/Pizzeria.java#L21-L24

**Comment by Romchansky** [comment]
Исправил на обычный цикл for чтобы каждая пицца выводилась последовательно.
