### ISSUE TITLE
Применять форматирование кода 

### ISSUE THREAD

**Issue by Bratchvv** [Romchansky/brain-acad-labs#3]
1) Необходимо применять форматирование кода (alt+ctrl+L)
2) Необходимо убирать ненужные отступы, пробелы, переносы и т д.  

https://github.com/Romchansky/brain-acad-labs/blob/d217649025e0d5fdacc1322b7f047c091f720c2d/Lab10/src/ua/zp/brainacad/Library.java#L27-L32

**Comment by Romchansky** [comment]
Применил редактирование к тексту, стоит делать пропуск одной строки между разными методами?
